import spectacleOne from '../../assets/icons/spectacleIcons/spectacleOne.jpg'
import spectacleTwo from '../../assets/icons/spectacleIcons/spectalce7.jpg'
import spectacleThree from '../../assets/icons/spectacleIcons/_rvs8202-1000x-e54.jpg'
import spectacleFour from '../../assets/icons/spectacleIcons/spectacle4.jpg'
import spectacleFive from '../../assets/icons/spectacleIcons/spectacle5.jpg'
import spectacleSix from '../../assets/icons/spectacleIcons/spectacle6.jpg'
import foodOne from '../icons/food/oneFood.webp'
import foodTwo from '../icons/food/twoFood.webp'
import foodThree from '../icons/food/threeFood.webp'
import foodFour from '../icons/food/fourFood.webp'
import foodFive from '../icons/food/nineFood.webp'
import foodTwn from '../icons/food/tenFood.webp'
import foodEleven from '../icons/food/elevenFood.webp'
import foodTwelve from '../icons/food/twelveFood.webp'
import foodSix from '../icons/food/sixFood.webp'
import limon from '../icons/food/limonFood.webp'


export type MenuItem = {
    id: number;
    title: string;
    sectionId: string;

}

export const MenuAll: MenuItem[] = [
    { id: 5, title: 'Главная', sectionId: 'home' },
    { id: 2, title: 'Спектакли', sectionId: 'spectacle' },
    { id: 1, title: 'Меню', sectionId: 'menu' },
    { id: 4, title: 'Контакты', sectionId: 'contacts' },
];


export const foodData = [
    {id: 20, imageFood: foodOne, comment: 'Рыба-император с креветочным кремом ', cost: 3300, quantity: 1},
    {id: 21, imageFood: foodTwo, comment: 'Филе дорадо со спаржей и вонголе', cost: 3000, quantity: 1},
    {id: 22, imageFood: foodThree, comment: 'Равиоли с лососем в соусе из печеной', cost: 2600, quantity: 1},
    {id: 23, imageFood: foodFour, comment: 'Крем-суп из тыквы с тортеллини из телятины', cost: 900, quantity: 1},
    {id: 24, imageFood: foodFive, comment: 'Кальмар на гриле', cost: 1200, quantity: 1},
    {id: 25, imageFood: foodSix, comment: 'Цыпленок с кускусом и молодой морковью', cost: 2400, quantity: 1},
    {id: 26, imageFood: foodTwn, comment: 'Рибай с перечным соусом', cost: 5200, quantity: 1},
    {id: 27, imageFood: foodEleven, comment: 'Аргентинские креветки на гриле', cost: 1900, quantity: 1},
    {id: 28, imageFood: foodTwelve, comment: 'Гребешок на гриле', cost: 2100, quantity: 1},
    {id: 29, imageFood: limon, comment: 'Лимонная сфера с медом и ромашкой', cost: 800, quantity: 1},
]

 export const wineData = [
     {id: 11, wineName: 'Riesling Liberated from alcohol, Hans Baer' , cost: 5000 , overview: ' 750 мл бутылка', quantity: 1 },
     {id: 12, wineName: 'Ballet Blanc, Galitsky & Galitsky' , cost: 10000 , overview: ' 750 мл бутылка', quantity: 1 },
     {id: 13, wineName: 'Shiraz Camden Park, Byrne Vineyards' , cost: 5300, overview: ' 750 мл бутылка', quantity: 1 },
     {id: 14, wineName: 'Chianti Colli Senesi, Fattoria Del Cerro' , cost: 8000 , overview: ' 750 мл бутылка', quantity: 1 },
     {id: 15, wineName: 'Malbec, Luigi Bosca' , cost: 10000 , overview: ' 750 мл бутылка', quantity: 1 },
     {id: 16, wineName: 'Hertz Semigorye, Sikory' , cost: 5000 , overview: ' 750 мл бутылка', quantity: 1 },
     {id: 17, wineName: 'Petit Chablis, Olivier Tricon' , cost: 12000 , overview: ' 750 мл бутылка', quantity: 1 },
     {id: 18, wineName: 'Petit Chablis, Olivier Tricon' , cost: 12000 , overview: ' 750 мл бутылка', quantity: 1 },
     {id: 19, wineName: 'Petit Chablis, Olivier Tricon' , cost:  12000 , overview: ' 750 мл бутылка', quantity: 1 },
]

export const drinks = [
    {id: 20, drinkName: 'Сок  Апельсин / Вишня / Яблоко / Ананас' , cost: 200 , overview: ' 250 мл ', quantity: 1 },
    {id: 21, drinkName: 'Зеленый чай' , cost: 250 , overview: ' 500 мл ', quantity: 1 },
    {id: 22, drinkName: 'Жасминовый чай' , cost: 150, overview: ' 500 мл ', quantity: 1 },
    {id: 23, drinkName: 'Красный чай' , cost: 250 , overview: ' 500 мл ', quantity: 1 },
    {id: 24, drinkName: 'Мин. вода Легенда Байкала (без газа)' , cost: 300 , overview: ' 750 мл ', quantity: 1 },
    {id: 25, drinkName: 'Кола EVERVESS' , cost: 350 , overview: ' 330 мл ', quantity: 1 },
    {id: 25, drinkName: 'Латте' , cost: 250 , overview: 'Кофе 200 мл ', quantity: 1 },
    {id: 25, drinkName: 'Раф' , cost: 240 , overview: 'Кофе 200 мл ', quantity: 1 },

]

export const SpectacleData = [

    {
        id: 1,
        icons: spectacleOne,
        age: '18+',
        hall: [
            [
                {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 4, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 9, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 12, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 5, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 16, reserved: true, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 95000},
            ],
            [
                {row: 'D', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 3, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
            ],
            [
                {row: 'E', seatNumber: 1, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 6, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 13, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 15, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 18, reserved: true, color: '#0d4f63', costPlace: 8000},
            ],
            [
                {row: 'G', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 22, reserved: false, color: '#73d3f4', costPlace: 5000},
            ],
            [
                {row: 'H', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
            ]
        ],
        dates: [
            {id: 1, date: '2025-01-01 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
            {id: 1, date: '2025-01-05 ', time: '18:00', cost: '5000 ₽-11000 ₽'},
            {id: 1, date: '2025-01-10 ', time: '19:00', cost: '5000 ₽-11000 ₽'},
            {id: 1, date: '2025-01-15 ', time: '14:00', cost: '5000 ₽-11000 ₽'},
            {id: 1, date: '2025-01-21 ', time: '14:00', cost: '5000 ₽-11000 ₽'},
        ],
        adress: ['м.Бауманская, Спартаковская пл., 9/1'],
        title: '\n' +
            'Вероника решает…\n' +
            '\n',
        comment: '«Вероника решает» — это уникальная интерпретация мирового бестселлера Пауло Коэльо, предложенная режиссером.\n' +
            '\n' +
            'Глубокая и трогательная история о стремлении жить, чувствовать и верить.\n' +
            '\n' +
            'Герои этой постановки, сталкиваясь с самыми скрытыми желаниями и страхами, заново учатся понимать мир, который постоянно бросает им вызов.\n' +
            '\n' +
            'Как обрести веру в себя, когда кажется, что выхода больше нет? Какие неожиданные повороты может преподнести жизнь? Готовы ли мы раскрыть ее сокровенные тайны и встретить настоящую любовь?\n' +
            '\n' +
            'Спектакль наполнен любовью к жизни и верой в человека.\n' +
            '\n' +
            '«Для меня это самое жизнеутверждающее произведение Коэльо. В разные моменты нашей жизни мы воспринимаем этот мир и своё место в нём по-разному, переживая внутренние конфликты. Но всегда важно верить в свою жизненную силу. Только любовь и близкие люди могут помочь нам преодолеть любые трудности. Нужно учиться ценить жизнь и верить в себя».'
    },
    {
        id: 2,
        icons: spectacleTwo,
        age: '18+',
        hall: [
            [
                {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 14, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 16, reserved: true, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 2, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 4, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 14, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 17, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
            ],
            [
                {row: 'D', seatNumber: 1, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 2, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 4, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 14, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
            ],
            [
                {row: 'E', seatNumber: 1, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 6, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 13, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 15, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 18, reserved: true, color: '#0d4f63', costPlace: 8000},
            ],
            [
                {row: 'G', seatNumber: 1, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 3, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 8, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 17, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 22, reserved: false, color: '#73d3f4', costPlace: 5000},
            ],
            [
                {row: 'H', seatNumber: 1, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 2, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 9, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 20, reserved: true, color: '#73d3f4', costPlace: 5000},
            ]
        ],
        dates: [
            {id: 1, date: '2025-01-02 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
            {id: 2, date: '2025-01-06 ', time: '18:00', cost: '5000 ₽-11000 ₽'},
            {id: 3, date: '2025-01-11 ', time: '19:00', cost: '5000 ₽-11000 ₽'},
            {id: 4, date: '2025-01-18 ', time: '14:00', cost: '5000 ₽-11000 ₽'},
            {id: 5, date: '2025-01-22 ', time: '14:00', cost: '5000 ₽-11000 ₽'},

        ],
        adress: ['м.Бауманская, Спартаковская пл., 9/1'],
        title: 'Страсти по Торчалову',
        comment: '«Страсти по Торчалову» — это трогательная и глубокая трагикомедия о жизни, любви и вечных человеческих ценностях.\n' +
            '\n' +
            'Главные герои — люди из разных эпох, каждый из которых несет свой жизненный груз, свои ценности и ориентиры. Они неожиданно оказываются «застрявшими» между двумя мирами, где им предстоит откровенно взглянуть на самих себя. Этот путь требует признания ошибок и принятия сложных решений.\n' +
            '\n' +
            'Эта динамичная и увлекательная история наполнена неожиданными поворотами, остроумными диалогами и моментами, в которых смешное переплетается с трогательным. Сюжет изобилует искренними беседами, юмором и глубокими переживаниями.\n' +
            '\n' +
            'Что определяет человеческую жизнь, и кто контролирует нашу судьбу? Являются ли высшие силы ответственными за наш выбор, или же вся ответственность лежит на нас самих?\n' +
            '\n' +
            'Постановка раскрывает темы великой любви к жизни, великодушия и предательства, сострадания и веры в лучшее в человеке.'
    },
    {
        id: 4,
        icons: spectacleFour,
        age: '18+',
        hall: [
            [
                {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 4, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 9, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 12, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 5, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 16, reserved: true, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9000},
                {row: 'C', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 95000},
                {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
            ],
            [
                {row: 'D', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 3, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
            ],
            [
                {row: 'E', seatNumber: 1, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 6, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 13, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 15, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 18, reserved: true, color: '#0d4f63', costPlace: 8000},
            ],
            [
                {row: 'G', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 22, reserved: false, color: '#73d3f4', costPlace: 5000},
            ],
            [
                {row: 'H', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
            ]
        ],
        dates: [
            {id: 1, date: '2025-01-03 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
            {id: 2, date: '2025-01-07 ', time: '18:00', cost: '5000 ₽-11000 ₽'},
            {id: 3, date: '2025-01-12 ', time: '19:00', cost: '5000 ₽-11000 ₽'},
            {id: 4, date: '2025-01-19 ', time: '14:00', cost: '5000 ₽-11000 ₽'},
            {id: 5, date: '2025-01-23 ', time: '14:00', cost: '5000 ₽-11000 ₽'},

        ],
        adress: ['м.Бауманская, Спартаковская пл., 9/1'],
        title: 'ПЕТР I',
        comment: '«ПЕТР» (Петр Первый) — первый спектакль грандиозной трилогии «Антихрист и Христос».\n' +
            '\n' +
            'Сюжет строится вокруг противоречивой фигуры царя Петра Первого, который вызывал у своих современников самые полярные чувства — от благоговения до страха. Антихрист или Христос, свет или тьма — кем был этот правитель для своей страны? Что он оставил нам, своим потомкам — добро или зло?\n' +
            '\n' +
            'Каковы последствия для России от стремления следовать «западным стандартам», пренебрегая собственными традициями и аутентичностью?'
    },
    {
        id: 3,
        icons: spectacleThree,
        age: '16+',
        hall: [
            [
                {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 9, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 5, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 2, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 4, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 6, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
            ],
            [
                {row: 'D', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 3, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 18, reserved: true, color: '#145a17', costPlace: 9500},
            ],
            [
                {row: 'E', seatNumber: 1, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 6, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 13, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 15, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 18, reserved: false, color: '#0d4f63', costPlace: 8000},
            ],
            [
                {row: 'G', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 22, reserved: false, color: '#73d3f4', costPlace: 5000},
            ],
            [
                {row: 'H', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
            ]
        ],
        dates: [
            {id: 1, date: '2025-01-01 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
            {id: 2, date: '2025-01-05 ', time: '18:00', cost: '5000 ₽-11000 ₽'},
            {id: 3, date: '2025-01-10 ', time: '19:00', cost: '5000 ₽-11000 ₽'},
            {id: 4, date: '2025-01-17 ', time: '14:00', cost: '5000 ₽-11000 ₽'},
            {id: 5, date: '2025-01-21 ', time: '14:00', cost: '5000 ₽-11000 ₽'},
            {id: 6, date: '2025-01-30 ', time: '17:00', cost: '5000 ₽-11000 ₽'},
            {id: 7, date: '2025-02-07 ', time: '19:00', cost: ' 5000 ₽-11000 ₽'},
            {id: 8, date: '2025-02-12 ', time: '13:30', cost: '5000 ₽-11000 ₽'},
            {id: 9, date: '2025-02-21 ', time: '20:30', cost: '5000 ₽-11000 ₽'},
            {id: 10, date: '2025-02-22 ', time: '20:00', cost: '5000 ₽-11000 ₽'},
            {id: 11, date: '2025-02-28 ', time: '16:00', cost: '5000 ₽-11000 ₽'},
        ],
        adress: ['м.Бауманская, Спартаковская пл., 9/1'],
        title: 'Страсти по Торчалову',
        comment: '«Страсти по Торчалову» — это тонкая и лиричная трагикомедия, исследующая вопросы жизни, любви и человеческих ценностей.\n' +
            '\n' +
            'Герои постановки — персонажи из разных эпох, каждый из которых несет свой уникальный жизненный опыт и моральные ориентиры. Они оказываются в странной и неожиданной ситуации: застряли между двумя мирами. Там им предстоит честно взглянуть в лицо своим ошибкам и принять важные, а порой непростые решения.\n' +
            '\n' +
            'Сюжет богат на неожиданные повороты, проникновенные диалоги, остроумные моменты и трогательные сцены, которые держат зрителя в напряжении от начала до конца.\n' +
            '\n' +
            'Что определяет нашу жизнь, и кто на самом деле управляет нашей судьбой? Являются ли высшие силы теми, кто направляет нас, или же вся ответственность лежит в наших собственных руках?\n' +
            '\n' +
            'Спектакль посвящен глубоким темам: любви к жизни, предательству и великодушию, состраданию и вере в лучшее, что есть в каждом из нас.'
    },
    {
        id: 5,
        icons: spectacleFive,
        age: '18+',
        hall: [
            [
                {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 4, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 9, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 12, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 5, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 16, reserved: true, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 15, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
            ],
            [
                {row: 'D', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 3, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
            ],
            [
                {row: 'E', seatNumber: 1, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 6, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 13, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 15, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 18, reserved: true, color: '#0d4f63', costPlace: 8000},
            ],
            [
                {row: 'G', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 10, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 20, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 22, reserved: true, color: '#73d3f4', costPlace: 5000},
            ],
            [
                {row: 'H', seatNumber: 1, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 5, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 12, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
            ]
        ],
        dates: [
            {id: 1, date: '2025-01-04 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
            {id: 2, date: '2025-01-08 ', time: '18:00', cost: '5000 ₽-11000 ₽'},
            {id: 3, date: '2025-01-13 ', time: '19:00', cost: '5000 ₽-11000 ₽'},
            {id: 4, date: '2025-01-19 ', time: '14:00', cost: '5000 ₽-11000 ₽'},
            {id: 5, date: '2025-01-24 ', time: '14:00', cost: '5000 ₽-11000 ₽'},

        ],
        adress: ['м.Бауманская, Спартаковская пл., 9/1'],
        title: 'Цветы нам не нужны', comment: '\n' +
            '"Не хочу раскрывать все детали нового спектакля, но скажу так: я считаю Нюрнбергский процесс одним из ключевых событий XX века. Он стал отправной точкой для значительных перемен в мировом сообществе. Если вы или ваши дети мало знакомы с этим событием, спектакль «Цветы нам не нужны» даст вам возможность расширить свои знания, что крайне важно для любого современного образованного человека.\n' +
            '\n' +
            'Это история, охватывающая период с 1946 по 1966 годы — время стремительных изменений: Нюрнбергский процесс, Вьетнамская война, полёт Юрия Гагарина, Карибский кризис, развитие мирового кино и многое другое. Я хочу обсудить с вами, что изменилось в мире после этого судебного процесса. Как отреагировали четыре главные державы — Россия, Англия, Франция и Америка? Ведь они подписали пакт о взаимопомощи не только на время войны. А что мы видим сегодня? Многие пытаются переписать историю, забывая о том, какой ценой СССР завоевал победу над фашизмом. Спектакль напоминает о подвиге и Великой Победе советского народа в борьбе с нацизмом.\n' +
            '\n' +
            'Это откровенный диалог об истории, людях и нас с вами".'
    },

    {
        id: 6,
        icons: spectacleSix,
        age: '16+',
        hall: [
            [
                {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 4, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 9, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 12, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 5, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                {row: 'B', seatNumber: 16, reserved: true, color: '#a840ac', costPlace: 11000},
            ],
            [
                {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
            ],
            [
                {row: 'D', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 3, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                {row: 'D', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
            ],
            [
                {row: 'E', seatNumber: 1, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 6, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 13, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 15, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                {row: 'E', seatNumber: 18, reserved: true, color: '#0d4f63', costPlace: 8000},
            ],
            [
                {row: 'G', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'G', seatNumber: 22, reserved: false, color: '#73d3f4', costPlace: 5000},
            ],
            [
                {row: 'H', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                {row: 'H', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
            ]
        ],
        dates: [
            {id: 1, date: '2025-01-05 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
            {id: 2, date: '2025-01-05 ', time: '18:00', cost: '5000 ₽-11000 ₽'},
            {id: 3, date: '2025-01-10 ', time: '19:00', cost: '5000 ₽-11000 ₽'},
            {id: 4, date: '2025-01-17 ', time: '14:00', cost: '5000 ₽-11000 ₽'},
            {id: 5, date: '2025-01-21 ', time: '14:00', cost: '5000 ₽-11000 ₽'},

        ],
        adress: ['м.Бауманская, Спартаковская пл., 9/1'],
        title: "Война и мир", comment: '\n' +
            '«Война и мир. Русский Пьер» — уникальная театральная постановка.\n' +
            '\n' +
            'В спектакле задействована вся труппа театра, а также приглашённые актёры. В общей сложности на сцене выступят около семидесяти человек, включая известный Хор имени Свешникова. Хор исполнит проникновенные духовные песни, православные гимны, а также произведения западноевропейской музыки, сопровождая действие на протяжении всего спектакля.\n' +
            '\n' +
            'Для постановки художник создала 423 костюма, отражающие эпоху, описанную в романе. Военные мундиры, бальные платья и тщательно проработанные детали полностью соответствуют духу времени. Гримеры проделали огромную работу, воссоздав образы героев той эпохи. В спектакле использованы оригинальные световые решения.\n' +
            '\n' +
            'Спектакль «Война и мир» охватывает ключевые сюжетные линии великого романа, акцентируя внимание на истории Пьера Безухова — его пути от «западника» до русского патриота, от Пьера до Петра Кирилловича. В его внутренней борьбе, поисках истины и сомнениях отразилась Россия начала XIX века: поклонение западным идеям, война с Францией, увлечение масонством и, в конечном счёте, осознание истинной силы своего народа. Пьер постигает, что мощь России заключается в духовных ценностях простых людей — в их милосердии, правде и семейных традициях.\n' +
            '\n' +
            'На сцене также оживают судьбы ключевых персонажей русского дворянства: Андрея Болконского, Наташи Ростовой, Анатоля Курагина, Фёдора Долохова, Марьи Болконской, графов Ростовых, старого князя Болконского и Элен Безуховой.\n' +
            '\n' +
            'Любовь и страсть, светские интриги и простая жизнь народа, духовные искания и личные драмы, смена мировоззрений и поиск истинного смысла, времена мира и войны — все эти темы романа Льва Толстого перенесены на сцену.'
    },
]