
const Database = require('better-sqlite3');

const db = new Database('mydb.db');

db.exec(`
  CREATE TABLE IF NOT EXISTS drinks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    drinkName TEXT NOT NULL,
    cost REAL NOT NULL,
    overview TEXT,
    quantity REAL NOT NULL,
    category TEXT NOT NULL
  )
`);

db.exec(`
  CREATE TABLE IF NOT EXISTS food (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    imageFood TEXT NOT NULL,
    comment TEXT NOT NULL,
    cost REAL NOT NULL,
    quantity REAL NOT NULL
  )
`);
db.exec(`
CREATE TABLE IF NOT EXISTS spectacles (
    id INTEGER PRIMARY KEY,
    icons TEXT,
    age TEXT,
    hall TEXT,          -- JSON со схемой зала (каждый seat: {row, seatNumber, reserved, ...})
    dates TEXT,         -- JSON с массивом дат
    adress TEXT,        -- JSON с адресом или чем-то похожим
    title TEXT,
    comment TEXT,
    reservedSeats TEXT  -- JSON-объект вида { "2025-01-10": [{row, seatNumber}, ...], ... }
);
`);


db.prepare(`
  CREATE TABLE IF NOT EXISTS reservations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,       -- 'YYYY-MM-DD'
    tableId INTEGER NOT NULL,
    isReserved INTEGER NOT NULL DEFAULT 1
  )
`).run();

const foodCount = db.prepare(`SELECT COUNT(*) as count FROM food`).get().count;
if (foodCount === 0) {
    db.exec(`
    INSERT INTO food (imageFood, comment, cost, quantity)
    VALUES
    ('https://i.postimg.cc/xCqnGSZt/eleven-Food.webp', 'Аргентинские креветки на гриле', 1900, 1),
      ('https://i.postimg.cc/J75Cy0tM/fourFood.webp', 'Крем-суп из тыквы с тортеллини', 900, 1),
      ('https://i.postimg.cc/Cxt3yfrH/limon-Food.webp', 'Лимонная сфера с медом и ромашкой', 800, 1),
      ('https://i.postimg.cc/CMN9h26K/nineFood.webp', 'Кальмар на гриле', 1200, 1),
      ('https://i.postimg.cc/ht9Lnkpy/oneFood.webp', 'Рыба-император с креветочным кремом', 3300, 1),
      ('https://i.postimg.cc/JnhZbGmv/tenFood.webp', 'Рибай с перечным соусом', 4500, 1),
      ('https://i.postimg.cc/q7w2h8f2/sixFood.webp', 'Цыпленок с кускусом и молодой морковью', 2700, 1),
      ('https://i.postimg.cc/dtCdmMPs/three-Food.webp', 'Равиоли с лососем в соусе', 2700, 1);
  `);

    console.log('Данные в таблицу "food" добавлены (seed).');
}

const drinksCount = db.prepare(`SELECT COUNT(*) as count FROM drinks`).get().count;
if (drinksCount === 0) {
    db.exec(`
    INSERT INTO drinks (drinkName, cost, overview, quantity, category)
    VALUES
       ('Сок апельсиновый (Низкое содержание сахара)', 200, '250 мл', 1, 'Соки'),
       ('Сок яблочный (Низкое содержание сахара)', 200, '250 мл', 1, 'Соки'),
       ('Сок грейпфрутовый (Низкое содержание сахара)', 200, '250 мл', 1, 'Соки'),
       ('Сок ананасовый (Низкое содержание сахара)', 200, '250 мл', 1, 'Соки'),
       ('Сок томатный (Низкое содержание сахара)', 200, '250 мл', 1, 'Соки'),
      ('Чай зелёный', 250, '500 мл', 1,'Чай'),
      ('Чай Жасминовый', 150, '500 мл', 1,'Чай'),
      ('Чай красный', 250, '500 мл', 1,'Чай'),
      ('Чай черный', 250, '500 мл', 1,'Чай'),
      ('Мин. вода Легенда Байкала (без газа)', 300, '750 мл', 1,'Вода'),
      ('Мин. вода Легенда Байкала (c газом)', 300, '750 мл', 1,'Вода'),
      ('Добрый кола (содержание сахара)', 350, '330 мл', 1, 'Напитки' ),
      ('Добрый Манго-Маракуйя (содержание сахара)', 350, '330 мл', 1, 'Напитки'),
      ('Добрый Апельсин (содержание сахара)', 350, '330 мл', 1, 'Напитки'),
      ('Добрый Лимон-Лайм (содержание сахара)', 350, '330 мл', 1, 'Напитки' ),
      ('Латте', 250, '200 мл', 1, 'Кофе'),
      ('Раф', 240, '200 мл', 1, 'Кофе'),
      ('Капучино', 240, '200 мл', 1,'Кофе');
  `);

    console.log('Данные в таблицу "drinks" добавлены (seed).');
}

db.exec(`
  CREATE TABLE IF NOT EXISTS addition (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    additionName TEXT NOT NULL,
    cost REAL NOT NULL,
    quantity REAL NOT NULL
  )
`);

const additionCount = db.prepare(`SELECT COUNT(*) as count FROM addition`).get().count;
if (additionCount === 0) {
    db.exec(`
      INSERT INTO addition (additionName, cost, quantity)
      VALUES
         ('Бинокль', 1000, 1),
         ('Программу спектакля', 1000, 1)
    `);

    console.log('Данные в таблицу "addition" добавлены (seed).');
}


const spectaclesCount = db.prepare(`SELECT COUNT(*) as count FROM spectacles`).get().count;
if (spectaclesCount === 0) {

    const spectaclesData = [
        {
            id: 1,
            icons: 'https://i.postimg.cc/HxVN6j23/spectacle-One.jpg',
            age: '18+',
            hall: [
                [
                    {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 4, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 9, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 12, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 5, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 16, reserved: true, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'D', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 3, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'E', seatNumber: 1, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 6, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 13, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 15, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 18, reserved: true, color: '#0d4f63', costPlace: 8000},
                ],
                [
                    {row: 'G', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 22, reserved: false, color: '#73d3f4', costPlace: 5000},
                ],
                [
                    {row: 'H', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                ]
            ],
            dates: [
                {id: 1, date: '01.05.2025 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
                {id: 2, date: '09.05.2025  ', time: '18:00', cost: '5000 ₽-11000 ₽'},
                {id: 3, date: '18.05.2025  ', time: '19:00', cost: '5000 ₽-11000 ₽'},
                {id: 4, date: '24.05.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},
                {id: 5, date: '28.05.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},
                {id: 6, date: '12.06.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},


            ],
            adress: ['м.Бауманская, Спартаковская пл., 9/1'],
            title: '\n' +
                'Вероника решает…\n' +
                '\n',
            comment: '«Вероника решает» — это уникальная интерпретация мирового бестселлера Пауло Коэльо, предложенная режиссером.\n' +
                '\n' +
                'Глубокая и трогательная история о стремлении жить, чувствовать и верить.\n' +
                '\n' +
                'Герои этой постановки, сталкиваясь с самыми скрытыми желаниями и страхами, заново учатся понимать мир, который постоянно бросает им вызов.\n' +
                '\n' +
                'Как обрести веру в себя, когда кажется, что выхода больше нет? Какие неожиданные повороты может преподнести жизнь? Готовы ли мы раскрыть ее сокровенные тайны и встретить настоящую любовь?\n' +
                '\n' +
                'Спектакль наполнен любовью к жизни и верой в человека.\n' +
                '\n' +
                '«Для меня это самое жизнеутверждающее произведение Коэльо. В разные моменты нашей жизни мы воспринимаем этот мир и своё место в нём по-разному, переживая внутренние конфликты. Но всегда важно верить в свою жизненную силу. Только любовь и близкие люди могут помочь нам преодолеть любые трудности. Нужно учиться ценить жизнь и верить в себя».'
        },
        {
            id: 2,
            icons: 'https://i.postimg.cc/NjBPWdDK/spectalce7.jpg',
            age: '18+',
            hall: [
                [
                    {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 14, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 16, reserved: true, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 2, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 4, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 14, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 17, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'D', seatNumber: 1, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 2, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 4, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 14, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'E', seatNumber: 1, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 6, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 13, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 15, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 18, reserved: true, color: '#0d4f63', costPlace: 8000},
                ],
                [
                    {row: 'G', seatNumber: 1, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 3, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 8, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 17, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 22, reserved: false, color: '#73d3f4', costPlace: 5000},
                ],
                [
                    {row: 'H', seatNumber: 1, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 2, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 9, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 20, reserved: true, color: '#73d3f4', costPlace: 5000},
                ]
            ],
            dates: [
                {id: 1, date: '02.05.2025 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
                {id: 2, date: '10.05.2025  ', time: '18:00', cost: '5000 ₽-11000 ₽'},
                {id: 3, date: '19.05.2025  ', time: '19:00', cost: '5000 ₽-11000 ₽'},
                {id: 4, date: '25.05.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},
                {id: 5, date: '29.05.2025  ', time: '19:00', cost: '5000 ₽-11000 ₽'},
                {id: 6, date: '13.06.2025  ', time: '20:00', cost: '5000 ₽-11000 ₽'},
            ],
            adress: ['м.Бауманская, Спартаковская пл., 9/1'],
            title: 'Затерянный мир',
            comment: 'Постановка переносит юных зрителей в самое сердце опасных и манящих джунглей Южной Америки. Кого же встретят первооткрыватели на своем пути?... Далее\n' +
                'Попасть в удивительный мир дикой природы, встретиться лицом к лицу с гигантскими динозаврами, ящерами и дружелюбными мохнатыми гориллами... Спектакль "Затерянный мир" станет незабываемым приключением для всей семьи!\n' +
                '\n' +
                'Вас ждут яркие костюмы и живые декорации, потрясающая музыка, много юмора и отважные герои!'
        },
        {
            id: 4,
            icons: 'https://i.postimg.cc/1zz7z4LP/spectacle4.jpg',
            age: '18+',
            hall: [
                [
                    {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 4, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 9, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 12, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 5, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 16, reserved: true, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9000},
                    {row: 'C', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'D', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 3, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'E', seatNumber: 1, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 6, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 13, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 15, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 18, reserved: true, color: '#0d4f63', costPlace: 8000},
                ],
                [
                    {row: 'G', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 22, reserved: false, color: '#73d3f4', costPlace: 5000},
                ],
                [
                    {row: 'H', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                ]
            ],
            dates: [
                {id: 1, date: '03.05.2025 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
                {id: 2, date: '11.05.2025  ', time: '18:00', cost: '5000 ₽-11000 ₽'},
                {id: 3, date: '20.05.2025  ', time: '19:00', cost: '5000 ₽-11000 ₽'},
                {id: 4, date: '26.05.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},
                {id: 5, date: '26.05.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},
                {id: 6, date: '30.05.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},
            ],
            adress: ['м.Бауманская, Спартаковская пл., 9/1'],
            title: 'ПЕТР I',
            comment: '«ПЕТР» (Петр Первый) — первый спектакль грандиозной трилогии «Антихрист и Христос».\n' +
                '\n' +
                'Сюжет строится вокруг противоречивой фигуры царя Петра Первого, который вызывал у своих современников самые полярные чувства — от благоговения до страха. Антихрист или Христос, свет или тьма — кем был этот правитель для своей страны? Что он оставил нам, своим потомкам — добро или зло?\n' +
                '\n' +
                'Каковы последствия для России от стремления следовать «западным стандартам», пренебрегая собственными традициями и аутентичностью?'
        },
        {
            id: 3,
            icons: 'https://i.postimg.cc/L661wffH/spectacle6.jpg',
            age: '16+',
            hall: [
                [
                    {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 9, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 5, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 2, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 4, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 6, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'D', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 3, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 18, reserved: true, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'E', seatNumber: 1, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 6, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 13, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 15, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 18, reserved: false, color: '#0d4f63', costPlace: 8000},
                ],
                [
                    {row: 'G', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 22, reserved: false, color: '#73d3f4', costPlace: 5000},
                ],
                [
                    {row: 'H', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                ]
            ],
            dates: [
                {id: 1, date: '04.05.2025 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
                {id: 2, date: '12.05.2025  ', time: '18:00', cost: '5000 ₽-11000 ₽'},
                {id: 3, date: '21.05.2025  ', time: '19:00', cost: '5000 ₽-11000 ₽'},
                {id: 4, date: '27.05.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},
                {id: 5, date: '01.06.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},
            ],
            adress: ['м.Бауманская, Спартаковская пл., 9/1'],
            title: 'Страсти по Торчалову',
            comment: '«Страсти по Торчалову» — это тонкая и лиричная трагикомедия, исследующая вопросы жизни, любви и человеческих ценностей.\n' +
                '\n' +
                'Герои постановки — персонажи из разных эпох, каждый из которых несет свой уникальный жизненный опыт и моральные ориентиры. Они оказываются в странной и неожиданной ситуации: застряли между двумя мирами. Там им предстоит честно взглянуть в лицо своим ошибкам и принять важные, а порой непростые решения.\n' +
                '\n' +
                'Сюжет богат на неожиданные повороты, проникновенные диалоги, остроумные моменты и трогательные сцены, которые держат зрителя в напряжении от начала до конца.\n' +
                '\n' +
                'Что определяет нашу жизнь, и кто на самом деле управляет нашей судьбой? Являются ли высшие силы теми, кто направляет нас, или же вся ответственность лежит в наших собственных руках?\n' +
                '\n' +
                'Спектакль посвящен глубоким темам: любви к жизни, предательству и великодушию, состраданию и вере в лучшее, что есть в каждом из нас.'
        },
        {
            id: 5,
            icons: 'https://i.postimg.cc/Mp3bd5F2/spectacle5.jpg',
            age: '18+',
            hall: [
                [
                    {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 4, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 9, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 12, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 5, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 16, reserved: true, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 15, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'D', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 3, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'E', seatNumber: 1, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 6, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 13, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 15, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 18, reserved: true, color: '#0d4f63', costPlace: 8000},
                ],
                [
                    {row: 'G', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 10, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 20, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 22, reserved: true, color: '#73d3f4', costPlace: 5000},
                ],
                [
                    {row: 'H', seatNumber: 1, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 5, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 12, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                ]
            ],
            dates: [
                {id: 1, date: '05.05.2025 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
                {id: 2, date: '13.05.2025  ', time: '18:00', cost: '5000 ₽-11000 ₽'},
                {id: 3, date: '22.05.2025  ', time: '19:00', cost: '5000 ₽-11000 ₽'},
                {id: 4, date: '28.05.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},
                {id: 5, date: '02.06.2025  ', time: '20:00', cost: '5000 ₽-11000 ₽'},
            ],
            adress: ['м.Бауманская, Спартаковская пл., 9/1'],
            title: 'Цветы нам не нужны', comment: '\n' +
                '"Не хочу раскрывать все детали нового спектакля, но скажу так: я считаю Нюрнбергский процесс одним из ключевых событий XX века. Он стал отправной точкой для значительных перемен в мировом сообществе. Если вы или ваши дети мало знакомы с этим событием, спектакль «Цветы нам не нужны» даст вам возможность расширить свои знания, что крайне важно для любого современного образованного человека.\n' +
                '\n' +
                'Это история, охватывающая период с 1946 по 1966 годы — время стремительных изменений: Нюрнбергский процесс, Вьетнамская война, полёт Юрия Гагарина, Карибский кризис, развитие мирового кино и многое другое. Я хочу обсудить с вами, что изменилось в мире после этого судебного процесса. Как отреагировали четыре главные державы — Россия, Англия, Франция и Америка? Ведь они подписали пакт о взаимопомощи не только на время войны. А что мы видим сегодня? Многие пытаются переписать историю, забывая о том, какой ценой СССР завоевал победу над фашизмом. Спектакль напоминает о подвиге и Великой Победе советского народа в борьбе с нацизмом.\n' +
                '\n' +
                'Это откровенный диалог об истории, людях и нас с вами".'
        },

        {
            id: 6,
            icons: 'https://i.postimg.cc/fWd2yGg3/rvs8202-1000x-e54.jpg',
            age: '16+',
            hall: [
                [
                    {row: 'A', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 3, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 4, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 5, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 6, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 7, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 8, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 9, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 10, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 11, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 12, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 15, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'A', seatNumber: 16, reserved: false, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'B', seatNumber: 1, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 2, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 3, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 4, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 5, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 6, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 7, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 8, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 9, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 10, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 11, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 12, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 13, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 14, reserved: false, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 15, reserved: true, color: '#a840ac', costPlace: 11000},
                    {row: 'B', seatNumber: 16, reserved: true, color: '#a840ac', costPlace: 11000},
                ],
                [
                    {row: 'C', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 3, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 5, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 9, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 10, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 12, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 13, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'C', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'D', seatNumber: 1, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 2, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 3, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 4, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 5, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 6, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 7, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 8, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 9, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 10, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 11, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 12, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 13, reserved: true, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 14, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 15, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 16, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 17, reserved: false, color: '#145a17', costPlace: 9500},
                    {row: 'D', seatNumber: 18, reserved: false, color: '#145a17', costPlace: 9500},
                ],
                [
                    {row: 'E', seatNumber: 1, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 2, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 3, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 4, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 5, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 6, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 7, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 8, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 9, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 10, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 11, reserved: true, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 12, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 13, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 14, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 15, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 16, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 17, reserved: false, color: '#0d4f63', costPlace: 8000},
                    {row: 'E', seatNumber: 18, reserved: true, color: '#0d4f63', costPlace: 8000},
                ],
                [
                    {row: 'G', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'G', seatNumber: 22, reserved: false, color: '#73d3f4', costPlace: 5000},
                ],
                [
                    {row: 'H', seatNumber: 1, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 2, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 3, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 4, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 5, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 6, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 7, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 8, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 9, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 10, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 11, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 12, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 13, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 14, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 15, reserved: true, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 16, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 17, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 18, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 19, reserved: false, color: '#73d3f4', costPlace: 5000},
                    {row: 'H', seatNumber: 20, reserved: false, color: '#73d3f4', costPlace: 5000},
                ]
            ],
            dates: [
                {id: 1, date: '06.05.2025 ', time: '18:30', cost: '5000 ₽-11000 ₽'},
                {id: 2, date: '14.05.2025  ', time: '18:00', cost: '5000 ₽-11000 ₽'},
                {id: 3, date: '23.05.2025  ', time: '19:00', cost: '5000 ₽-11000 ₽'},
                {id: 4, date: '29.05.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},
                {id: 5, date: '29.05.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},
                {id: 5, date: '04.06.2025  ', time: '14:00', cost: '5000 ₽-11000 ₽'},

            ],
            adress: ['м.Бауманская, Спартаковская пл., 9/1'],
            title: "Война и мир", comment: '\n' +
                '«Война и мир. Русский Пьер» — уникальная театральная постановка.\n' +
                '\n' +
                'В спектакле задействована вся труппа театра, а также приглашённые актёры. В общей сложности на сцене выступят около семидесяти человек, включая известный Хор имени Свешникова. Хор исполнит проникновенные духовные песни, православные гимны, а также произведения западноевропейской музыки, сопровождая действие на протяжении всего спектакля.\n' +
                '\n' +
                'Для постановки художник создала 423 костюма, отражающие эпоху, описанную в романе. Военные мундиры, бальные платья и тщательно проработанные детали полностью соответствуют духу времени. Гримеры проделали огромную работу, воссоздав образы героев той эпохи. В спектакле использованы оригинальные световые решения.\n' +
                '\n' +
                'Спектакль «Война и мир» охватывает ключевые сюжетные линии великого романа, акцентируя внимание на истории Пьера Безухова — его пути от «западника» до русского патриота, от Пьера до Петра Кирилловича. В его внутренней борьбе, поисках истины и сомнениях отразилась Россия начала XIX века: поклонение западным идеям, война с Францией, увлечение масонством и, в конечном счёте, осознание истинной силы своего народа. Пьер постигает, что мощь России заключается в духовных ценностях простых людей — в их милосердии, правде и семейных традициях.\n' +
                '\n' +
                'На сцене также оживают судьбы ключевых персонажей русского дворянства: Андрея Болконского, Наташи Ростовой, Анатоля Курагина, Фёдора Долохова, Марьи Болконской, графов Ростовых, старого князя Болконского и Элен Безуховой.\n' +
                '\n' +
                'Любовь и страсть, светские интриги и простая жизнь народа, духовные искания и личные драмы, смена мировоззрений и поиск истинного смысла, времена мира и войны — все эти темы романа Льва Толстого перенесены на сцену.'
        },
    ];

    const insertStmt = db.prepare(`
      INSERT INTO spectacles 
      (id, icons, age, hall, dates, adress, title, comment)
      VALUES (@id, @icons, @age, @hall, @dates, @adress, @title, @comment)
    `);

    for (const spec of spectaclesData) {
        insertStmt.run({
            id: spec.id,
            icons: spec.icons,
            age: spec.age,
            hall: JSON.stringify(spec.hall),
            dates: JSON.stringify(spec.dates),
            adress: JSON.stringify(spec.adress),
            title: spec.title,
            comment: spec.comment,
        });
    }

    console.log('Данные в таблицу "spectacles" добавлены (seed).');
}


module.exports = db;

